baseURL = "https://phdbuilds.tech"
title = "PhDbuilds.tech"
author = "Logan Norris"
theme = "hello-friend-ng"
languageCode = "en"
defaultContentLanguage = "en"
enableInlineShortcodes = true
sectionPagesMenu = "main"
ignoreErrors = ["error-remote-getjson"]
copyright = "© [Logan Norris](https://phdbuilds.tech)"

[pagination]
  pagerSize = 10

[params]
  dateform = "Jan 2, 2006"
  dateformShort = "Jan 2"
  dateformNum = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
  homeSubtitle = "By Logan Norris"
  description = "Notes, builds, and hacking thoughts from Logan Norris."
  keywords = "cybersecurity, red team, hacking, linux, books, blog"
  images = [""]
  noindex = false
  defaultTheme = "dark"
  enableSharingButtons = true
  disableReadOtherPosts = false
  enableGlobalLanguageMenu = true

  [[params.social]]
    name = "GitHub"
    url = "https://github.com/phdbuilds"
    icon = "fa-brands fa-github"
  
  [[params.social]]
    name = "Email"
    url = "mailto:blnorris777@gmail.com"
    icon = "fa-solid fa-envelope"
  
  [[params.social]]
    name = "ORCID"
    url = "https://orcid.org/0000-0001-2345-6789"
    icon = "ai ai-orcid"

  [[params.author]]
    name = "Logan Norris"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "lib"
    name = "Lib"
    url = "/lib/"
    weight = 20


[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 2
  endLevel = 3
  ordered = true

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

